name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        auto-activate-base: false
        channels: conda-forge

    - name: Install dependencies
      run: mamba install yarn flake8 jupyterlab jupyterlab-lsp

    - name: Install JS dependencies
      run: yarn install
      working-directory: json_lsp

    - name: Install json-lsp
      run: pip install .

    - name: Test flake8
      run: flake8 json_lsp

    - name: Test json-lsp
      run: which json-lsp
